-- ============================================================
-- Banco de dados do site da Kerllen Rodrigues (Supabase)
-- Cole este script no Supabase: SQL Editor > New query > Run
-- ============================================================

-- ---------- TABELAS ----------
create table if not exists leads (
  id          bigint generated by default as identity primary key,
  nome        text not null,
  whatsapp    text,
  objetivo    text,
  created_at  timestamptz default now()
);

create table if not exists pacientes (
  id          bigint generated by default as identity primary key,
  nome        text not null,
  telefone    text,
  email       text,
  nascimento  date,
  objetivo    text,
  status      text default 'ativo',
  anamnese    text default 'pendente',
  metas       text,
  created_at  timestamptz default now()
);

create table if not exists anamneses (
  id          bigint generated by default as identity primary key,
  nome        text,
  telefone    text,
  sexo        text,
  idade       int,
  respostas   jsonb,
  treinos     jsonb,
  created_at  timestamptz default now()
);

create table if not exists consultas (
  id           bigint generated by default as identity primary key,
  paciente_id  bigint references pacientes(id) on delete cascade,
  data         date,
  resumo       text,
  created_at   timestamptz default now()
);

create table if not exists evolucao (
  id           bigint generated by default as identity primary key,
  paciente_id  bigint references pacientes(id) on delete cascade,
  data         date,
  peso         numeric,
  obs          text,
  created_at   timestamptz default now()
);

-- ---------- SEGURANÇA (Row Level Security) ----------
alter table leads     enable row level security;
alter table pacientes enable row level security;
alter table anamneses enable row level security;
alter table consultas enable row level security;
alter table evolucao  enable row level security;

-- Qualquer visitante pode ENVIAR um lead ou uma anamnese (formularios publicos)
create policy "public insere leads"     on leads     for insert to anon        with check (true);
create policy "public insere anamneses" on anamneses for insert to anon        with check (true);

-- Somente usuarios logados (a nutricionista) leem/gerenciam tudo
create policy "logado gerencia leads" on leads     for all    to authenticated using (true) with check (true);
create policy "logado le anamneses"  on anamneses for select to authenticated using (true);
create policy "logado gerencia pac"  on pacientes for all    to authenticated using (true) with check (true);
create policy "logado gerencia cons" on consultas for all    to authenticated using (true) with check (true);
create policy "logado gerencia evo"  on evolucao  for all    to authenticated using (true) with check (true);
